- type: job
  id: Captain
  name: job-name-captain
  description: job-description-captain
  playTimeTracker: JobCaptain
  requirements:
    - !type:DepartmentTimeRequirement
      department: Engineering
      time: 72000 # LPP-RoleTime
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 72000 # LPP-RoleTime
    - !type:DepartmentTimeRequirement
      department: Security
      time: 72000 # LPP-RoleTime
    - !type:DepartmentTimeRequirement
      department: Command
      time: 108000 # LPP-RoleTime
    - !type:OverallPlaytimeRequirement
      time: 288000 # LPP-RoleTime
  weight: 20
  startingGear: CaptainGear
  icon: "JobIconCaptain"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: CaptainGear
  equipment:
    shoes: ClothingShoesBootsLaceup
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesCaptain
    id: CaptainPDA
    ears: ClothingHeadsetAltCommand
  storage:
    back:
    - Flash
    # - StationCharter
    # - LPPTelebaton
