- type: department
  id: Cargo
  description: department-Cargo-description
  color: "#A46106"
  roles:
  - Quartermaster
  - SalvageSpecialist
  - CargoTechnician

- type: department
  id: Civilian
  description: department-Civilian-description
  color: "#9FED58"
  weight: -10
  roles:
  - HeadOfPersonnel
  - Bartender
  - Botanist
  - Boxer
  - Chaplain
  - Chef
  - Clown
  - Janitor
  - Librarian
  - Mime
  - Musician
  - Passenger
  - Reporter
  - Visitor
  - Zookeeper
  - ServiceWorker

- type: department
  id: Command
  description: department-Command-description
  color: "#334E6D"
  roles:
  # - Magistrate
  - Captain
  # - CentralCommandOfficial
  - ChiefEngineer
  - ChiefMedicalOfficer
  - HeadOfPersonnel
  - HeadOfSecurity
  - ResearchDirector
  - Quartermaster
  # - LPPAdjutant
  primary: false
  weight: 100

- type: department
  id: Engineering
  description: department-Engineering-description
  color: "#EFB341"
  roles:
  - ChiefEngineer
  - SeniorEngineer
  - AtmosphericTechnician
  - StationEngineer
  - TechnicalAssistant

- type: department
  id: Medical
  description: department-Medical-description
  color: "#52B4E9"
  roles:
  - ChiefMedicalOfficer
  - SeniorPhysician
  # - LPPVirologist
  - Chemist
  - MedicalDoctor
  - Paramedic
  - Psychologist
  - MedicalIntern

- type: department
  id: Security
  description: department-Security-description
  color: "#DE3A3A"
  weight: 20
  roles:
  - HeadOfSecurity
  - Warden
  - SeniorOfficer
  - Detective
  - SecurityOfficer
  # - LPPBrigmedic
  # - LPPSecurityEnginer
  # - SecPilot
  - SecurityCadet

- type: department
  id: CentCom
  description: department-Command-description
  color: "#49c423"
  roles:
  - CentralCommandOfficial
  # - LPPBlueShieldOfficer
  # - LPPCentralCommandRepresentative

- type: department
  id: Law
  description: department-Command-description
  color: "#de7e3a"
  roles:
  # - Magistrate
  - IAA
  - Lawyer

- type: department
  id: Science
  description: department-Science-description
  color: "#D381C9"
  roles:
  - ResearchDirector
  - SeniorResearcher
  - Borg
  - Scientist
  # - Roboticist
  - ResearchAssistant
  # - Expeditor

#- type: department
#  id: Specific
#  description: department-Specific-description
#  color: "#9FED58"
#  roles:
#  - Boxer
#  - Reporter
#  - Zookeeper
#  - Psychologist
